import { AIModelInfo } from '@/types'

export const AI_MODELS: AIModelInfo[] = [
  // ── Groq (fast, free, no credit card) ──
  {
    id: 'gpt-oss-120b',
    name: 'GPT-OSS 120B',
    provider: 'OpenAI via Groq',
    description: 'Large open-source model, recommended',
    icon: '⚡',
    color: '#10b981',
    speed: 'fast',
    free: true,
    maxTokens: 65536,
  },
  {
    id: 'gpt-oss-20b',
    name: 'GPT-OSS 20B',
    provider: 'OpenAI via Groq',
    description: 'Lightweight, blazing fast',
    icon: '⚡',
    color: '#10b981',
    speed: 'ultra-fast',
    free: true,
    maxTokens: 65536,
  },
  {
    id: 'llama-3.3-70b',
    name: 'Llama 3.3 70B',
    provider: 'Meta via Groq',
    description: 'Versatile, strong all-rounder',
    icon: '🦙',
    color: '#0668E1',
    speed: 'fast',
    free: true,
    maxTokens: 32768,
  },
  {
    id: 'qwen-3.8-27b',
    name: 'Qwen 3.8 27B',
    provider: 'Alibaba via Groq',
    description: 'Strong multilingual and reasoning',
    icon: '🌊',
    color: '#6366f1',
    speed: 'fast',
    free: true,
    maxTokens: 16384,
  },
  {
    id: 'qwen-3.6-27b',
    name: 'Qwen 3.6 27B',
    provider: 'Alibaba via Groq',
    description: 'Fast, versatile everyday model',
    icon: '🌊',
    color: '#6366f1',
    speed: 'ultra-fast',
    free: true,
    maxTokens: 16384,
  },
  {
    id: 'minimax-m2.7',
    name: 'MiniMax M2.7',
    provider: 'MiniMax via Groq',
    description: '196K context, strong reasoning',
    icon: '🧠',
    color: '#8b5cf6',
    speed: 'fast',
    free: true,
    maxTokens: 131072,
  },

  // ── Google Gemini (free, no credit card) ──
  {
    id: 'gemini-3.5-flash',
    name: 'Gemini 3.5 Flash',
    provider: 'Google',
    description: 'Latest fast Gemini, 1M context',
    icon: '✦',
    color: '#4285f4',
    speed: 'fast',
    free: true,
    maxTokens: 65536,
  },
  {
    id: 'gemini-3.7-flash',
    name: 'Gemini 3.7 Flash',
    provider: 'Google',
    description: 'Newest Gemini, multimodal',
    icon: '✦',
    color: '#4285f4',
    speed: 'fast',
    free: true,
    maxTokens: 65536,
  },
  {
    id: 'gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    provider: 'Google',
    description: 'Reasoning model, 1M context',
    icon: '✦',
    color: '#4285f4',
    speed: 'fast',
    free: true,
    maxTokens: 65536,
  },

  // ── Mistral AI (free mode, no credit card, $10/mo credits) ──
  {
    id: 'mistral-medium-3.5',
    name: 'Mistral Medium 3.5',
    provider: 'Mistral AI',
    description: '128B, text + code + vision',
    icon: '🌀',
    color: '#ff7000',
    speed: 'fast',
    free: true,
    maxTokens: 262144,
  },
  {
    id: 'codestral',
    name: 'Codestral',
    provider: 'Mistral AI',
    description: 'Specialized coding model, 128K ctx',
    icon: '💻',
    color: '#ff7000',
    speed: 'fast',
    free: true,
    maxTokens: 131072,
  },

  // ── Hugging Face (free $0.10/mo credits, OpenAI-compatible) ──
  {
    id: 'hf-llama-3.1-8b',
    name: 'Llama 3.1 8B (HF)',
    provider: 'Hugging Face',
    description: 'Fast, via HF Inference API',
    icon: '🤗',
    color: '#ffd21e',
    speed: 'ultra-fast',
    free: true,
    maxTokens: 4096,
  },
  {
    id: 'hf-qwen2.5-7b',
    name: 'Qwen2.5 7B (HF)',
    provider: 'Hugging Face',
    description: 'Versatile, via HF Inference API',
    icon: '🤗',
    color: '#ffd21e',
    speed: 'ultra-fast',
    free: true,
    maxTokens: 4096,
  },

  // ── OpenRouter Free ──
  {
    id: 'llama-4-maverick',
    name: 'Llama 4 Maverick',
    provider: 'Meta via OpenRouter',
    description: '128-expert MoE, multimodal',
    icon: '🦙',
    color: '#0668E1',
    speed: 'fast',
    free: true,
    maxTokens: 4096,
  },
  {
    id: 'llama-4-scout',
    name: 'Llama 4 Scout',
    provider: 'Meta via OpenRouter',
    description: 'Efficient 16-expert MoE',
    icon: '🦙',
    color: '#0668E1',
    speed: 'ultra-fast',
    free: true,
    maxTokens: 4096,
  },
  {
    id: 'nemotron-ultra-550b',
    name: 'Nemotron Ultra 550B',
    provider: 'NVIDIA via OpenRouter',
    description: 'Massive 550B, top-tier reasoning',
    icon: '🟢',
    color: '#76b900',
    speed: 'moderate',
    free: true,
    maxTokens: 4096,
  },
  {
    id: 'nemotron-3.5-lightning',
    name: 'Nemotron 3.5 Lightning',
    provider: 'NVIDIA via OpenRouter',
    description: 'Ultra-fast, 1M context',
    icon: '⚡',
    color: '#76b900',
    speed: 'ultra-fast',
    free: true,
    maxTokens: 4096,
  },
  {
    id: 'nemotron-super-120b',
    name: 'Nemotron Super 120B',
    provider: 'NVIDIA via OpenRouter',
    description: 'Balanced speed and quality',
    icon: '🟢',
    color: '#76b900',
    speed: 'fast',
    free: true,
    maxTokens: 4096,
  },
  {
    id: 'deepseek-v4-flash',
    name: 'DeepSeek V4 Flash',
    provider: 'DeepSeek via OpenRouter',
    description: 'Latest DeepSeek, free & fast',
    icon: '🔍',
    color: '#0066FF',
    speed: 'fast',
    free: true,
    maxTokens: 4096,
  },
  {
    id: 'gemma-4-31b',
    name: 'Gemma 4 31B',
    provider: 'Google via OpenRouter',
    description: 'Google open-source, vision capable',
    icon: '✦',
    color: '#4285f4',
    speed: 'fast',
    free: true,
    maxTokens: 4096,
  },
  {
    id: 'gemma-4-26b',
    name: 'Gemma 4 26B',
    provider: 'Google via OpenRouter',
    description: 'Compact Google model, vision capable',
    icon: '✦',
    color: '#4285f4',
    speed: 'ultra-fast',
    free: true,
    maxTokens: 4096,
  },
  {
    id: 'cohere-north-mini',
    name: 'Cohere North Mini',
    provider: 'Cohere via OpenRouter',
    description: 'Code-focused, developer-friendly',
    icon: '💻',
    color: '#39d353',
    speed: 'ultra-fast',
    free: true,
    maxTokens: 4096,
  },
  {
    id: 'inclusionai-ling',
    name: 'Ling 3.0 Flash',
    provider: 'Inclusion AI via OpenRouter',
    description: '262K context, fast multilingual',
    icon: '💡',
    color: '#f59e0b',
    speed: 'fast',
    free: true,
    maxTokens: 4096,
  },
  {
    id: 'poolside-laguna',
    name: 'Laguna S 2.1',
    provider: 'Poolside via OpenRouter',
    description: 'Code-specialized, 262K context',
    icon: '🌊',
    color: '#06b6d4',
    speed: 'fast',
    free: true,
    maxTokens: 4096,
  },
  {
    id: 'openrouter-free',
    name: 'Plurix V1',
    provider: 'OpenRouter',
    description: 'Auto-routes to best available free model',
    icon: '✦',
    color: '#8b5cf6',
    speed: 'fast',
    free: true,
    maxTokens: 4096,
  },
]

export function getModelById(id: string): AIModelInfo | undefined {
  return AI_MODELS.find(m => m.id === id)
}

export function getFreeModels(): AIModelInfo[] {
  return AI_MODELS.filter(m => m.free)
}
