import { AIModelInfo } from '@/types'

export const AI_MODELS: AIModelInfo[] = [
  {
    id: 'mimo-v2-flash',
    name: 'MiMo V2 Flash',
    provider: 'Xiaomi',
    description: '309B MoE model, ultra-fast reasoning and coding',
    icon: '📱',
    color: '#ff6700',
    speed: 'ultra-fast',
    free: true,
    maxTokens: 8192,
  },
  {
    id: 'gemini-2.0-flash',
    name: 'Gemini 2.0 Flash',
    provider: 'Google',
    description: 'Fast, versatile, great for everyday tasks',
    icon: '✦',
    color: '#4285f4',
    speed: 'ultra-fast',
    free: true,
    maxTokens: 8192,
  },
  {
    id: 'gemini-2.5-pro',
    name: 'Gemini 2.5 Pro',
    provider: 'Google',
    description: 'Most capable Gemini, best for complex reasoning',
    icon: '✦',
    color: '#34a853',
    speed: 'fast',
    free: true,
    maxTokens: 65536,
  },
  {
    id: 'llama-3.3-70b',
    name: 'Llama 3.3 70B',
    provider: 'Meta via Groq',
    description: 'Open-source giant, ultra-fast inference',
    icon: '🦙',
    color: '#7c3aed',
    speed: 'ultra-fast',
    free: true,
    maxTokens: 8192,
  },
  {
    id: 'llama-3.1-8b',
    name: 'Llama 3.1 8B',
    provider: 'Meta via Groq',
    description: 'Lightweight, blazing fast responses',
    icon: '🦙',
    color: '#a855f7',
    speed: 'ultra-fast',
    free: true,
    maxTokens: 8192,
  },
  {
    id: 'mixtral-8x7b',
    name: 'Mixtral 8x7B',
    provider: 'Mistral via Groq',
    description: 'Mixture of experts, strong multilingual',
    icon: '🌀',
    color: '#f97316',
    speed: 'ultra-fast',
    free: true,
    maxTokens: 8192,
  },
  {
    id: 'gpt-4o-mini',
    name: 'GPT-4o Mini',
    provider: 'OpenAI',
    description: 'Affordable, fast, surprisingly capable',
    icon: '⚡',
    color: '#10b981',
    speed: 'fast',
    free: true,
    maxTokens: 16384,
  },
  {
    id: 'claude-3.5-sonnet',
    name: 'Claude 3.5 Sonnet',
    provider: 'Anthropic',
    description: 'Best for writing, analysis, and coding',
    icon: '🧠',
    color: '#d97706',
    speed: 'moderate',
    free: true,
    maxTokens: 8192,
  },
  {
    id: 'deepseek-chat',
    name: 'DeepSeek V3',
    provider: 'DeepSeek',
    description: 'Strong reasoning, excellent for math/code',
    icon: '🔍',
    color: '#06b6d4',
    speed: 'fast',
    free: true,
    maxTokens: 8192,
  },
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    provider: 'OpenAI',
    description: 'Most capable OpenAI model, multimodal',
    icon: '🤖',
    color: '#10b981',
    speed: 'moderate',
    free: false,
    maxTokens: 16384,
  },
  {
    id: 'qwen-turbo',
    name: 'Qwen Turbo',
    provider: 'Alibaba',
    description: 'Fast, good multilingual support',
    icon: '🌊',
    color: '#6366f1',
    speed: 'ultra-fast',
    free: true,
    maxTokens: 8192,
  },
  {
    id: 'mistral-large',
    name: 'Mistral Large',
    provider: 'Mistral AI',
    description: 'Premium open-weight model, strong performer',
    icon: '💨',
    color: '#ef4444',
    speed: 'fast',
    free: true,
    maxTokens: 12288,
  },
]

export function getModelById(id: string): AIModelInfo | undefined {
  return AI_MODELS.find(m => m.id === id)
}

export function getFreeModels(): AIModelInfo[] {
  return AI_MODELS.filter(m => m.free)
}
