import { AIModelInfo } from '@/types'

export const AI_MODELS: AIModelInfo[] = [
  // ── Groq models (fast, free) ──
  {
    id: 'gpt-oss-120b',
    name: 'GPT-OSS 120B',
    provider: 'OpenAI via Groq',
    description: 'Large open-source model, recommended',
    icon: '⚡',
    color: '#10b981',
    speed: 'fast',
    free: true,
    maxTokens: 8192,
  },
  {
    id: 'llama-4-maverick',
    name: 'Llama 4 Maverick',
    provider: 'Meta via Groq',
    description: 'Latest Meta Llama, best quality',
    icon: '🦙',
    color: '#0668E1',
    speed: 'fast',
    free: true,
    maxTokens: 8192,
  },
  {
    id: 'llama-4-scout',
    name: 'Llama 4 Scout',
    provider: 'Meta via Groq',
    description: 'Fast and efficient Llama 4',
    icon: '🦙',
    color: '#0668E1',
    speed: 'ultra-fast',
    free: true,
    maxTokens: 8192,
  },
  {
    id: 'llama-3.3-70b',
    name: 'Llama 3.3 70B',
    provider: 'Meta via Groq',
    description: 'Versatile, strong all-rounder',
    icon: '🦙',
    color: '#0668E1',
    speed: 'fast',
    free: true,
    maxTokens: 8192,
  },
  {
    id: 'deepseek-r1',
    name: 'DeepSeek R1',
    provider: 'DeepSeek via Groq',
    description: 'Advanced reasoning and analysis',
    icon: '🔍',
    color: '#0066FF',
    speed: 'fast',
    free: true,
    maxTokens: 8192,
  },
  {
    id: 'deepseek-v3',
    name: 'DeepSeek V3',
    provider: 'DeepSeek via Groq',
    description: 'Fast, strong coding and math',
    icon: '🔍',
    color: '#0066FF',
    speed: 'ultra-fast',
    free: true,
    maxTokens: 8192,
  },
  {
    id: 'qwen-3.8-27b',
    name: 'Qwen 3.8 27B',
    provider: 'Alibaba via Groq',
    description: 'Strong multilingual and reasoning',
    icon: '🌊',
    color: '#6366f1',
    speed: 'ultra-fast',
    free: true,
    maxTokens: 8192,
  },
  {
    id: 'qwen-3.6-27b',
    name: 'Qwen 3.6 27B',
    provider: 'Alibaba via Groq',
    description: 'Fast, versatile everyday model',
    icon: '🌊',
    color: '#6366f1',
    speed: 'ultra-fast',
    free: true,
    maxTokens: 8192,
  },
  {
    id: 'gpt-oss-20b',
    name: 'GPT-OSS 20B',
    provider: 'OpenAI via Groq',
    description: 'Lightweight, blazing fast',
    icon: '⚡',
    color: '#10b981',
    speed: 'ultra-fast',
    free: true,
    maxTokens: 8192,
  },
  {
    id: 'allam-2-7b',
    name: 'Allam 2 7B',
    provider: 'Groq',
    description: 'Lightweight and fast',
    icon: '🌀',
    color: '#f97316',
    speed: 'ultra-fast',
    free: true,
    maxTokens: 4096,
  },

  // ── Google Gemini ──
  {
    id: 'gemini-3.5-flash',
    name: 'Gemini 3.5 Flash',
    provider: 'Google',
    description: 'Reliable, fast Gemini model',
    icon: '✦',
    color: '#4285f4',
    speed: 'fast',
    free: true,
    maxTokens: 8192,
  },

  // ── OpenRouter free models ──
  {
    id: 'nemotron-ultra-550b',
    name: 'Nemotron Ultra 550B',
    provider: 'NVIDIA via OpenRouter',
    description: 'Massive 550B, top-tier reasoning',
    icon: '🟢',
    color: '#76b900',
    speed: 'moderate',
    free: true,
    maxTokens: 4096,
  },
  {
    id: 'nemotron-3.5-lightning',
    name: 'Nemotron 3.5 Lightning',
    provider: 'NVIDIA via OpenRouter',
    description: 'Ultra-fast, 1M context',
    icon: '⚡',
    color: '#76b900',
    speed: 'ultra-fast',
    free: true,
    maxTokens: 4096,
  },
  {
    id: 'nemotron-super-120b',
    name: 'Nemotron Super 120B',
    provider: 'NVIDIA via OpenRouter',
    description: 'Balanced speed and quality',
    icon: '🟢',
    color: '#76b900',
    speed: 'fast',
    free: true,
    maxTokens: 4096,
  },
  {
    id: 'gemma-4-31b',
    name: 'Gemma 4 31B',
    provider: 'Google via OpenRouter',
    description: 'Google open-source, strong all-rounder',
    icon: '✦',
    color: '#4285f4',
    speed: 'fast',
    free: true,
    maxTokens: 4096,
  },
  {
    id: 'gemma-4-26b',
    name: 'Gemma 4 26B',
    provider: 'Google via OpenRouter',
    description: 'Compact Google model, efficient',
    icon: '✦',
    color: '#4285f4',
    speed: 'ultra-fast',
    free: true,
    maxTokens: 4096,
  },
  {
    id: 'minimax-m3',
    name: 'MiniMax M3',
    provider: 'MiniMax via OpenRouter',
    description: '1M context, multilingual',
    icon: '🧠',
    color: '#8b5cf6',
    speed: 'fast',
    free: true,
    maxTokens: 4096,
  },
  {
    id: 'cohere-north-mini',
    name: 'Cohere North Mini',
    provider: 'Cohere via OpenRouter',
    description: 'Code-focused, developer-friendly',
    icon: '💻',
    color: '#39d353',
    speed: 'ultra-fast',
    free: true,
    maxTokens: 4096,
  },
  {
    id: 'inkling',
    name: 'Inkling',
    provider: 'Thinking Machines via OpenRouter',
    description: '1M context, creative and analytical',
    icon: '💡',
    color: '#f59e0b',
    speed: 'fast',
    free: true,
    maxTokens: 4096,
  },
  {
    id: 'openrouter-free',
    name: 'Auto (Best Free)',
    provider: 'OpenRouter',
    description: 'Routes to best available free model',
    icon: '🎲',
    color: '#8b5cf6',
    speed: 'fast',
    free: true,
    maxTokens: 4096,
  },
]

export function getModelById(id: string): AIModelInfo | undefined {
  return AI_MODELS.find(m => m.id === id)
}

export function getFreeModels(): AIModelInfo[] {
  return AI_MODELS.filter(m => m.free)
}
