import { Link } from 'react-router-dom'
import { ChevronLeft } from 'lucide-react'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-black">
      <div className="border-b border-white/[0.04] px-5 py-3 flex items-center gap-3">
        <Link to="/" className="p-1.5 rounded-lg hover:bg-white/[0.05] text-white/30 hover:text-white/60">
          <ChevronLeft size={16} />
        </Link>
        <h1 className="text-[15px] font-bold">Terms of Service</h1>
      </div>
      <div className="max-w-2xl mx-auto px-5 py-10">
        <p className="text-white/25 text-[11px] mb-8 uppercase tracking-wider font-medium">Last updated: August 27, 2026</p>

        <div className="space-y-8">
          <section>
            <h2 className="text-[15px] font-bold mb-2">1. Acceptance of Terms</h2>
            <p className="text-white/45 text-[13px] leading-relaxed">
              By accessing or using Plurix ("the Service"), you agree to be bound by these Terms of Service.
              If you do not agree, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-bold mb-2">2. Description of Service</h2>
            <p className="text-white/45 text-[13px] leading-relaxed">
              Plurix is a free AI-powered assistant that provides access to multiple language models including
              but not limited to GPT-4o, Claude, Gemini, Llama, and DeepSeek. The Service is provided "as is"
              at no cost to users.
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-bold mb-2">3. User Accounts</h2>
            <p className="text-white/45 text-[13px] leading-relaxed">
              You may create an account using email/password or OAuth (Google/GitHub). You are responsible for
              maintaining the security of your account. You must be at least 13 years old to use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-bold mb-2">4. Acceptable Use</h2>
            <p className="text-white/45 text-[13px] leading-relaxed">
              You agree NOT to use Plurix to generate harmful, illegal, or malicious content. This includes but
              is not limited to: malware, harassment, spam, copyright infringement, or any activity that violates
              applicable law. We reserve the right to ban users who violate these terms.
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-bold mb-2">5. Intellectual Property</h2>
            <p className="text-white/45 text-[13px] leading-relaxed">
              Content generated by AI models through Plurix is provided for informational purposes. You are
              responsible for verifying the accuracy of AI-generated content. Plurix does not claim ownership
              of user-generated content.
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-bold mb-2">6. Privacy</h2>
            <p className="text-white/45 text-[13px] leading-relaxed">
              Your use of the Service is also governed by our{' '}
              <Link to="/privacy" className="text-gold-400/70 hover:text-gold-400 transition-colors underline underline-offset-2">Privacy Policy</Link>.
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-bold mb-2">7. Disclaimer of Warranties</h2>
            <p className="text-white/45 text-[13px] leading-relaxed">
              THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. AI-generated content may contain
              errors. Always verify important information independently.
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-bold mb-2">8. Limitation of Liability</h2>
            <p className="text-white/45 text-[13px] leading-relaxed">
              Plurix and its operators shall not be liable for any indirect, incidental, special, or consequential
              damages arising from your use of the Service.
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-bold mb-2">9. Termination</h2>
            <p className="text-white/45 text-[13px] leading-relaxed">
              We reserve the right to suspend or terminate your access to the Service at any time for violation
              of these terms or for any other reason at our discretion.
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-bold mb-2">10. Changes to Terms</h2>
            <p className="text-white/45 text-[13px] leading-relaxed">
              We may update these terms at any time. Continued use of the Service after changes constitutes
              acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-bold mb-2">11. Contact</h2>
            <p className="text-white/45 text-[13px] leading-relaxed">
              Questions? Email us at{' '}
              <a href="mailto:legal@plurix.app" className="text-gold-400/70 hover:text-gold-400 transition-colors">legal@plurix.app</a>.
            </p>
          </section>
        </div>
      </div>
    </div>
  )
}
