import { Link } from 'react-router-dom'
import { ChevronLeft } from 'lucide-react'

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0a0a0f]">
      <div className="border-b border-white/5 px-6 py-4 flex items-center gap-4">
        <Link to="/" className="p-2 rounded-xl hover:bg-white/5 text-white/40 hover:text-white">
          <ChevronLeft size={18} />
        </Link>
        <h1 className="text-lg font-bold">Terms of Service</h1>
      </div>
      <div className="max-w-3xl mx-auto px-6 py-12 prose prose-invert">
        <p className="text-white/50 text-sm mb-8">Last updated: August 26, 2026</p>

        <h2 className="text-xl font-bold mb-4">1. Acceptance of Terms</h2>
        <p className="text-white/60 text-sm leading-relaxed mb-6">
          By accessing or using Plurix ("the Service"), you agree to be bound by these Terms of Service. 
          If you do not agree, do not use the Service.
        </p>

        <h2 className="text-xl font-bold mb-4">2. Description of Service</h2>
        <p className="text-white/60 text-sm leading-relaxed mb-6">
          Plurix is a free AI-powered assistant that provides access to multiple language models including 
          but not limited to GPT-4o, Claude, Gemini, Llama, and DeepSeek. The Service is provided "as is" 
          at no cost to users.
        </p>

        <h2 className="text-xl font-bold mb-4">3. User Accounts</h2>
        <p className="text-white/60 text-sm leading-relaxed mb-6">
          You may create an account using email/password or OAuth (Google/GitHub). You are responsible for 
          maintaining the security of your account. You must be at least 13 years old to use the Service.
        </p>

        <h2 className="text-xl font-bold mb-4">4. Acceptable Use</h2>
        <p className="text-white/60 text-sm leading-relaxed mb-6">
          You agree NOT to use Plurix to generate harmful, illegal, or malicious content. This includes but 
          is not limited to: malware, harassment, spam, copyright infringement, or any activity that violates 
          applicable law. We reserve the right to ban users who violate these terms.
        </p>

        <h2 className="text-xl font-bold mb-4">5. Intellectual Property</h2>
        <p className="text-white/60 text-sm leading-relaxed mb-6">
          Content generated by AI models through Plurix is provided for informational purposes. You are 
          responsible for verifying the accuracy of AI-generated content. Plurix does not claim ownership 
          of user-generated content.
        </p>

        <h2 className="text-xl font-bold mb-4">6. Privacy</h2>
        <p className="text-white/60 text-sm leading-relaxed mb-6">
          Your use of the Service is also governed by our{' '}
          <Link to="/privacy" className="text-blue-400 hover:text-blue-300">Privacy Policy</Link>.
        </p>

        <h2 className="text-xl font-bold mb-4">7. Disclaimer of Warranties</h2>
        <p className="text-white/60 text-sm leading-relaxed mb-6">
          THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. AI-generated content may contain 
          errors. Always verify important information independently.
        </p>

        <h2 className="text-xl font-bold mb-4">8. Limitation of Liability</h2>
        <p className="text-white/60 text-sm leading-relaxed mb-6">
          Plurix and its operators shall not be liable for any indirect, incidental, special, or consequential 
          damages arising from your use of the Service.
        </p>

        <h2 className="text-xl font-bold mb-4">9. Termination</h2>
        <p className="text-white/60 text-sm leading-relaxed mb-6">
          We reserve the right to suspend or terminate your access to the Service at any time for violation 
          of these terms or for any other reason at our discretion.
        </p>

        <h2 className="text-xl font-bold mb-4">10. Changes to Terms</h2>
        <p className="text-white/60 text-sm leading-relaxed mb-6">
          We may update these terms at any time. Continued use of the Service after changes constitutes 
          acceptance of the new terms.
        </p>

        <h2 className="text-xl font-bold mb-4">11. Contact</h2>
        <p className="text-white/60 text-sm leading-relaxed">
          Questions? Email us at{' '}
          <a href="mailto:legal@plurix.app" className="text-blue-400 hover:text-blue-300">legal@plurix.app</a>.
        </p>
      </div>
    </div>
  )
}
