// Vercel Serverless Function — routes chat to Groq + OpenRouter + Gemini
import type { VercelRequest, VercelResponse } from '@vercel/node'

type Provider = 'groq' | 'openrouter' | 'gemini'

const MODELS: Record<string, { provider: Provider; modelName: string }> = {
  // ── Groq Production ──
  'gpt-oss-120b':           { provider: 'groq', modelName: 'openai/gpt-oss-120b' },
  'gpt-oss-20b':            { provider: 'groq', modelName: 'openai/gpt-oss-20b' },
  'llama-3.3-70b':          { provider: 'groq', modelName: 'llama-3.3-70b-versatile' },
  'llama-3.1-8b':           { provider: 'groq', modelName: 'llama-3.1-8b-instant' },
  // ── Groq Preview ──
  'qwen-3.8-27b':           { provider: 'groq', modelName: 'qwen/qwen3.8-27b' },
  'qwen-3.6-27b':           { provider: 'groq', modelName: 'qwen/qwen3.6-27b' },
  'minimax-m2.7':           { provider: 'groq', modelName: 'minimaxai/minimax-m2.7' },
  // ── Google Gemini ──
  'gemini-3.5-flash':       { provider: 'gemini', modelName: 'gemini-2.0-flash' },
  // ── OpenRouter Free ──
  'llama-4-maverick':       { provider: 'openrouter', modelName: 'meta-llama/llama-4-maverick:free' },
  'llama-4-scout':          { provider: 'openrouter', modelName: 'meta-llama/llama-4-scout:free' },
  'nemotron-ultra-550b':    { provider: 'openrouter', modelName: 'nvidia/nemotron-3-ultra-550b-a55b:free' },
  'nemotron-3.5-lightning': { provider: 'openrouter', modelName: 'nvidia/nemotron-3.5-lightning:free' },
  'nemotron-super-120b':    { provider: 'openrouter', modelName: 'nvidia/nemotron-3-super-120b-a12b:free' },
  'deepseek-v4-flash':      { provider: 'openrouter', modelName: 'deepseek/deepseek-v4-flash:free' },
  'gemma-4-31b':            { provider: 'openrouter', modelName: 'google/gemma-4-31b-it:free' },
  'gemma-4-26b':            { provider: 'openrouter', modelName: 'google/gemma-4-26b-a4b-it:free' },
  'cohere-north-mini':      { provider: 'openrouter', modelName: 'cohere/north-mini-code:free' },
  'openrouter-free':        { provider: 'openrouter', modelName: 'openrouter/free' },
}

function getKey(provider: Provider): string {
  const map: Record<Provider, string> = {
    groq: 'GROQ_API_KEY',
    openrouter: 'OPENROUTER_API_KEY',
    gemini: 'GOOGLE_API_KEY',
  }
  return process.env[map[provider]] || ''
}

// Detect image generation requests
function isImageRequest(text: string): boolean {
  const lower = text.toLowerCase()
  return (
    lower.includes('generate image') ||
    lower.includes('create image') ||
    lower.includes('make image') ||
    lower.includes('draw') ||
    lower.includes('picture of') ||
    lower.includes('photo of') ||
    lower.includes('image of') ||
    lower.startsWith('an image') ||
    lower.startsWith('a picture') ||
    lower.startsWith('generate a') ||
    lower.startsWith('create a picture') ||
    lower.startsWith('make a picture') ||
    lower.startsWith('draw me')
  )
}

// Extract the image prompt from the user's message
function extractImagePrompt(text: string): string {
  return text
    .replace(/generate\s+(an?\s+)?image\s*(of|for)?\s*/i, '')
    .replace(/create\s+(an?\s+)?(image|picture|photo)\s*(of|for)?\s*/i, '')
    .replace(/make\s+(an?\s+)?(image|picture|photo)\s*(of|for)?\s*/i, '')
    .replace(/draw\s+(me\s+)?(an?\s+)?(a\s+)?/i, '')
    .replace(/picture\s+of\s*/i, '')
    .replace(/photo\s+of\s*/i, '')
    .replace(/image\s+of\s*/i, '')
    .trim() || text
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  res.setHeader('Access-Control-Allow-Origin', '*')
  res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS')
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type')
  if (req.method === 'OPTIONS') return res.status(200).end()
  if (req.method !== 'POST') return res.status(405).json({ error: 'Method not allowed' })

  const { messages, model, temperature = 0.7, files } = req.body || {}

  if (!messages || !Array.isArray(messages))
    return res.status(400).json({ error: 'messages array is required' })

  if (!model || !MODELS[model])
    return res.status(400).json({ error: `Unknown model: ${model}`, available: Object.keys(MODELS) })

  // Check if this is an image generation request
  const lastMsg = messages[messages.length - 1]
  if (lastMsg && lastMsg.role === 'user' && isImageRequest(lastMsg.content)) {
    const prompt = extractImagePrompt(lastMsg.content)
    const seed = Math.floor(Math.random() * 999999)
    const imageUrl = `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}?width=1024&height=1024&seed=${seed}&model=flux`
    return res.status(200).json({
      text: `🖼️ Here's your image:\n\n![${prompt}](${imageUrl})\n\n**Prompt:** ${prompt}\n**Generated by:** Pollination AI (free)`,
      model: 'pollination-flux',
      provider: 'pollination',
      image: imageUrl,
    })
  }

  const config = MODELS[model]
  const apiKey = getKey(config.provider)
  if (!apiKey)
    return res.status(503).json({ error: `${config.provider.toUpperCase()}_API_KEY not configured.` })

  // Build file context — read files and format them for the AI
  let processedMessages = [...messages]
  if (files && Array.isArray(files) && files.length > 0) {
    const fileParts: string[] = []
    for (const f of files) {
      const name = f.name || 'unknown-file'
      const type = f.type || 'unknown'
      const size = f.size || 0
      const content = f.content || ''

      if (content && content.trim()) {
        // Truncate very large files to avoid context overflow
        const maxChars = 50000
        const truncated = content.length > maxChars
          ? content.substring(0, maxChars) + `\n\n... [truncated, ${content.length} total chars]`
          : content
        fileParts.push(`📄 File: ${name} (${type}, ${Math.round(size / 1024)}KB)\n\`\`\`\n${truncated}\n\`\`\``)
      } else {
        fileParts.push(`📄 File: ${name} (${type}, ${Math.round(size / 1024)}KB) — binary file, content not readable as text`)
      }
    }

    if (fileParts.length > 0) {
      const fileContext = fileParts.join('\n\n')

      // Find the last user message and prepend file context
      const lastUserIdx = processedMessages.findLastIndex((m: any) => m.role === 'user')
      if (lastUserIdx >= 0) {
        const originalContent = processedMessages[lastUserIdx].content
        processedMessages[lastUserIdx] = {
          ...processedMessages[lastUserIdx],
          content: `The user has attached ${files.length} file(s) for you to analyze:\n\n${fileContext}\n\n---\n\nUser's message: ${originalContent}`,
        }
      } else {
        // No user message yet — add one with the files
        processedMessages.push({
          role: 'user',
          content: `Please analyze these attached files:\n\n${fileContext}`,
        })
      }

      // Add a system instruction to ensure the AI reads the files
      const hasSystem = processedMessages.some((m: any) => m.role === 'system')
      if (!hasSystem) {
        processedMessages.unshift({
          role: 'system',
          content: 'The user has attached files. Read and analyze them carefully. Reference specific content from the files in your response.',
        })
      }
    }
  }

  try {
    let responseText = ''

    if (config.provider === 'gemini') {
      const contents = processedMessages
        .filter((m: any) => m.role !== 'system')
        .map((m: any) => ({
          role: m.role === 'assistant' ? 'model' : 'user',
          parts: [{ text: m.content }],
        }))

      const systemMsg = processedMessages.find((m: any) => m.role === 'system')
      const payload: any = {
        contents,
        generationConfig: { temperature, maxOutputTokens: 4096 },
      }
      if (systemMsg) {
        payload.systemInstruction = { parts: [{ text: systemMsg.content }] }
      }

      const apiRes = await fetch(
        `https://generativelanguage.googleapis.com/v1beta/models/${config.modelName}:generateContent?key=${apiKey}`,
        { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }
      )
      if (!apiRes.ok) {
        const err = await apiRes.text()
        throw new Error(`Gemini error ${apiRes.status}: ${err.substring(0, 200)}`)
      }
      const data = await apiRes.json()
      responseText = data.candidates?.[0]?.content?.parts?.[0]?.text || ''

    } else {
      const endpoint = config.provider === 'groq'
        ? 'https://api.groq.com/openai/v1/chat/completions'
        : 'https://openrouter.ai/api/v1/chat/completions'

      const apiRes = await fetch(endpoint, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${apiKey}`,
          ...(config.provider === 'openrouter' ? { 'HTTP-Referer': 'https://plurix.app', 'X-Title': 'Plurix' } : {}),
        },
        body: JSON.stringify({
          model: config.modelName,
          messages: processedMessages,
          temperature,
          max_tokens: 4096,
        }),
      })

      const data = await apiRes.json()

      if (!apiRes.ok) {
        const errMsg = data?.error?.message || data?.error || JSON.stringify(data).substring(0, 200)
        throw new Error(`${config.provider} error ${apiRes.status}: ${errMsg}`)
      }

      responseText = data.choices?.[0]?.message?.content || ''
    }

    if (!responseText) responseText = 'No response received. Please try again.'

    return res.status(200).json({ text: responseText, model: config.modelName, provider: config.provider })

  } catch (err: any) {
    console.error(`[api/chat] ${model} (${config.provider}):`, err.message)
    return res.status(500).json({ error: err.message || 'Failed to generate response' })
  }
}
